### ISSUE TITLE
Onedrive download link

### ISSUE THREAD

**Issue by jingyibo123** [sjtuyinjie/SJTU_GVI#1]
Hi, 

Many thanks for the contribution and generous sharing.

I wonder if it's possible to provide onedrive download links like [M2DGR](https://github.com/SJTU-ViSYS/M2DGR) ?
That would be a lot more convenient..

**Comment by sjtuyinjie** [comment]
No problem. Data will be uploaded to Onedrive soon.

**Comment by sjtuyinjie** [comment]
Sorry but I've tried it just now and found that I could not get access to the Onedrive for unknown reason (maybe onedrive is blocked this moment).

**Comment by jingyibo123** [comment]
> Sorry but I've tried it just now and found that I could not get access to the Onedrive for unknown reason (maybe onedrive is blocked this moment).

Thanks a lot for the lightning fast response, maybe it's just the GFW at its glory.... It'd be great if you could try again whenever you got time

:)
