### ISSUE TITLE
Are these parameters right?

### ISSUE THREAD

**Issue by zzhh00** [sjtuyinjie/SJTU_GVI#3]
HI,
Firstly, thanks for your contribution. However I have check your parameters of D435i in M2DGR, they are different from the parameters in this dataset. Besides I used your parameters in this dataset to test open_vins, the result is very poor. Thus I am confused about which  dataset gives the right parameters. Wish for your reply.

**Comment by sjtuyinjie** [comment]
The cameras used in these  two datasets are not the same one. Both two datasets give the right parameters.
